// How the achiever categories are shown. achievers-data.ts is generated by
// scripts/generate-achievers.mjs and overwritten on every run, so display
// choices live here instead: the order the categories appear in, and names
// with consistent capitalisation (the source mixes "K-CET TOPPERS" with
// "NEET Top Achievers"). Names match the header menu.

import { type AchieverGroup, achieverGroups } from "./achievers-data";

const display: Record<string, { name: string; heading: string }> = {
  "jee-advanced": { name: "JEE Advanced", heading: "JEE Advanced Toppers" },
  "jee-mains": { name: "JEE Mains", heading: "JEE Mains Toppers" },
  neet: { name: "NEET", heading: "NEET Top Achievers" },
  "k-cet": { name: "K-CET", heading: "K-CET Toppers" },
  nstse: { name: "NSTSE & NTSE", heading: "NSTSE & NTSE Top Achievers" },
};

const order = Object.keys(display);

/** The categories in display order, with display names. A category the
 *  generator adds later still shows, at the end, under its source name. */
export const achieverSections: AchieverGroup[] = [...achieverGroups]
  .sort((a, b) => {
    const ia = order.indexOf(a.slug);
    const ib = order.indexOf(b.slug);
    return (ia === -1 ? order.length : ia) - (ib === -1 ? order.length : ib);
  })
  .map((g) => ({
    ...g,
    ...(display[g.slug] ?? {}),
    // The source quotes carry stray quotation marks ("…satisfaction.” - …").
    quote: g.quote.replace(/[“”"]/g, "").trim(),
  }));

export function sectionBySlug(slug: string) {
  return achieverSections.find((g) => g.slug === slug);
}

/**
 * Tidies a rank as the academy publishes it, without changing what it says:
 * a bare number becomes "Rank 309", and "AIR - 5942" / "State Rank - 4" lose
 * the stray dash.
 */
export function formatRank(rank: string) {
  const r = rank.trim();
  if (/^\d+$/.test(r)) return `Rank ${r}`;
  return r.replace(/\s*-\s*(?=\d)/g, " ").replace(/\s+/g, " ");
}
